#spin up two machines — one runs Flask using my code,
#one runs Postgres using an official image.
#Connect them so Flask can reach Postgres using the name db.
#Load my secrets from .env.
#Save the database data permanently so it doesn't disappear on restart.

services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis


#First machine is called web.
#Connect port 5000 on your laptop to port 5000 inside the container
#Load all the variables from your .env file and pass them into this container
#'db' is the name of the second container below — this is how Flask finds Postgres.
#Inside Docker, containers talk to each other using this service name.
#Don't start the web container until the db container is up first


  db:
    image: postgres:15
    environment:
      POSTGRES_DB: travel_app_db
      POSTGRES_USER: srikaaviyaramadeve
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  #Second machine - db. Don't build it — just download ready-made
  #Postgres 15 image from Docker Hub.
  #Postgres starts up, create a database and user with these credentials.
  #The volumes section is used to map storage locations.
  #The format is always [host_machine_location]:[container_internal_location].

#  This is a Bind Mount. (./init-db:/docker-entrypoint-initdb.d)
#  Explanation: The official PostgreSQL Docker image has a built-in startup script.
#  When the database boots up for the very first time,
#  it automatically checks the internal /docker-entrypoint-initdb.d directory and
#  executes any .sql or .sh files it finds there to set up
#  This line connects your local ./init-db folder to that internal directory,
#  allowing PostgreSQL to automatically run your custom database initialization scripts on startup.

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

#Docker runs the Celery worker command. -A tasks means "look in tasks.py for the tasks".
#  worker means "start listening for jobs".
# redis url — tells both Flask and Celery where the post box

volumes:
  postgres_data:


#Containers are temporary — if you stop and restart the db container,
#everything inside it disappears.
#This line says "save the database data to a permanent
#place called postgres_data on your laptop."






